# Generated by Django 4.2.13 on 2024-06-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actor',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
