# Generated by Django 4.2.13 on 2024-06-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movies_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='href',
            field=models.CharField(max_length=200),
        ),
    ]
